language: ruby
env:
  - JENKINS_VERSION=1.596.3
  - JENKINS_VERSION=1.609.3
  - JENKINS_VERSION=1.625.3
  - JENKINS_VERSION=latest
jdk:
  - oraclejdk8
  - openjdk7
  - openjdk6
rvm:
  - ruby
  - jruby-19mode # JRuby in 1.9 mode
sudo: false
